/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "device_audit-log": () => import("@/views/device/audit-log/index.vue"),
  device_feedback: () => import("@/views/device/feedback/index.vue"),
  device_payment: () => import("@/views/device/payment/index.vue"),
  device_printer: () => import("@/views/device/printer/index.vue"),
  device_review_detail: () => import("@/views/device/review/detail/index.vue"),
  device_review: () => import("@/views/device/review/index.vue"),
  dish_category: () => import("@/views/dish/category/index.vue"),
  dish_list: () => import("@/views/dish/list/index.vue"),
  dish_spec: () => import("@/views/dish/spec/index.vue"),
  home: () => import("@/views/home/index.vue"),
  log_login: () => import("@/views/log/login/index.vue"),
  log_operation: () => import("@/views/log/operation/index.vue"),
  manage_banner: () => import("@/views/manage/banner/index.vue"),
  manage_config: () => import("@/views/manage/config/index.vue"),
  manage_coupon: () => import("@/views/manage/coupon/index.vue"),
  manage_dict: () => import("@/views/manage/dict/index.vue"),
  "manage_member-user": () => import("@/views/manage/member-user/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  "manage_mq-message": () => import("@/views/manage/mq-message/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  manage_theme: () => import("@/views/manage/theme/index.vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  marketing_banner: () => import("@/views/marketing/banner/index.vue"),
  marketing_coupon: () => import("@/views/marketing/coupon/index.vue"),
  "marketing_member-benefit": () => import("@/views/marketing/member-benefit/index.vue"),
  "marketing_member-growth-record": () => import("@/views/marketing/member-growth-record/index.vue"),
  "marketing_member-level": () => import("@/views/marketing/member-level/index.vue"),
  "marketing_member-points-record": () => import("@/views/marketing/member-points-record/index.vue"),
  "marketing_member-stat": () => import("@/views/marketing/member-stat/index.vue"),
  marketing_member: () => import("@/views/marketing/member/index.vue"),
  monitor_message: () => import("@/views/monitor/message/index.vue"),
  order_detail: () => import("@/views/order/detail/index.vue"),
  order_list: () => import("@/views/order/list/index.vue"),
  "report_dish-ranking": () => import("@/views/report/dish-ranking/index.vue"),
  report_revenue: () => import("@/views/report/revenue/index.vue"),
  "report_table-turnover": () => import("@/views/report/table-turnover/index.vue"),
  service_checkout: () => import("@/views/service/checkout/index.vue"),
  service_kitchen: () => import("@/views/service/kitchen/index.vue"),
  "service_order-ops": () => import("@/views/service/order-ops/index.vue"),
  "service_place-order": () => import("@/views/service/place-order/index.vue"),
  "service_table-board": () => import("@/views/service/table-board/index.vue"),
  table_area: () => import("@/views/table/area/index.vue"),
  table_manage: () => import("@/views/table/manage/index.vue"),
};
