/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'device',
    path: '/device',
    component: 'layout.base',
    meta: {
      title: '设备与日志',
      icon: 'mdi:printer-outline',
      order: 6,
      i18nKey: 'route.device'
    },
    children: [
      {
        name: 'device_audit-log',
        path: '/device/audit-log',
        component: 'view.device_audit-log',
        meta: {
          title: '审计日志',
          icon: 'mdi:file-document-outline',
          i18nKey: 'route.device_audit-log'
        }
      },
      {
        name: 'device_feedback',
        path: '/device/feedback',
        component: 'view.device_feedback',
        meta: {
          title: 'device_feedback',
          i18nKey: 'route.device_feedback'
        }
      },
      {
        name: 'device_payment',
        path: '/device/payment',
        component: 'view.device_payment',
        meta: {
          title: 'device_payment',
          i18nKey: 'route.device_payment'
        }
      },
      {
        name: 'device_printer',
        path: '/device/printer',
        component: 'view.device_printer',
        meta: {
          title: '打印机管理',
          icon: 'mdi:printer',
          i18nKey: 'route.device_printer'
        }
      },
      {
        name: 'device_review',
        path: '/device/review',
        component: 'view.device_review',
        meta: {
          title: 'device_review',
          i18nKey: 'route.device_review'
        },
        children: [
          {
            name: 'device_review_detail',
            path: '/device/review/detail',
            component: 'view.device_review_detail',
            meta: {
              title: 'device_review_detail',
              i18nKey: 'route.device_review_detail'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'dish',
    path: '/dish',
    component: 'layout.base',
    meta: {
      title: '菜品管理',
      icon: 'mdi:food',
      order: 2,
      i18nKey: 'route.dish'
    },
    children: [
      {
        name: 'dish_category',
        path: '/dish/category',
        component: 'view.dish_category',
        meta: {
          title: 'dish_category',
          i18nKey: 'route.dish_category'
        }
      },
      {
        name: 'dish_list',
        path: '/dish/list',
        component: 'view.dish_list',
        meta: {
          title: 'dish_list',
          i18nKey: 'route.dish_list'
        }
      },
      {
        name: 'dish_spec',
        path: '/dish/spec',
        component: 'view.dish_spec',
        meta: {
          title: 'dish_spec',
          i18nKey: 'route.dish_spec'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_login',
        path: '/log/login',
        component: 'view.log_login',
        meta: {
          title: 'log_login',
          i18nKey: 'route.log_login'
        }
      },
      {
        name: 'log_operation',
        path: '/log/operation',
        component: 'view.log_operation',
        meta: {
          title: 'log_operation',
          i18nKey: 'route.log_operation'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: '系统管理',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_banner',
        path: '/manage/banner',
        component: 'view.manage_banner',
        meta: {
          title: 'manage_banner',
          i18nKey: 'route.manage_banner'
        }
      },
      {
        name: 'manage_config',
        path: '/manage/config',
        component: 'view.manage_config',
        meta: {
          title: 'manage_config',
          i18nKey: 'route.manage_config'
        }
      },
      {
        name: 'manage_coupon',
        path: '/manage/coupon',
        component: 'view.manage_coupon',
        meta: {
          title: 'manage_coupon',
          i18nKey: 'route.manage_coupon'
        }
      },
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict'
        }
      },
      {
        name: 'manage_member-user',
        path: '/manage/member-user',
        component: 'view.manage_member-user',
        meta: {
          title: 'manage_member-user',
          i18nKey: 'route.manage_member-user'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_mq-message',
        path: '/manage/mq-message',
        component: 'view.manage_mq-message',
        meta: {
          title: 'manage_mq-message',
          i18nKey: 'route.manage_mq-message'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_theme',
        path: '/manage/theme',
        component: 'view.manage_theme',
        meta: {
          title: 'manage_theme',
          i18nKey: 'route.manage_theme'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      }
    ]
  },
  {
    name: 'marketing',
    path: '/marketing',
    component: 'layout.base',
    meta: {
      title: 'marketing',
      i18nKey: 'route.marketing'
    },
    children: [
      {
        name: 'marketing_banner',
        path: '/marketing/banner',
        component: 'view.marketing_banner',
        meta: {
          title: 'marketing_banner',
          i18nKey: 'route.marketing_banner'
        }
      },
      {
        name: 'marketing_coupon',
        path: '/marketing/coupon',
        component: 'view.marketing_coupon',
        meta: {
          title: 'marketing_coupon',
          i18nKey: 'route.marketing_coupon'
        }
      },
      {
        name: 'marketing_member',
        path: '/marketing/member',
        component: 'view.marketing_member',
        meta: {
          title: 'marketing_member',
          i18nKey: 'route.marketing_member'
        }
      },
      {
        name: 'marketing_member-benefit',
        path: '/marketing/member-benefit',
        component: 'view.marketing_member-benefit',
        meta: {
          title: 'marketing_member-benefit',
          i18nKey: 'route.marketing_member-benefit'
        }
      },
      {
        name: 'marketing_member-growth-record',
        path: '/marketing/member-growth-record',
        component: 'view.marketing_member-growth-record',
        meta: {
          title: 'marketing_member-growth-record',
          i18nKey: 'route.marketing_member-growth-record'
        }
      },
      {
        name: 'marketing_member-level',
        path: '/marketing/member-level',
        component: 'view.marketing_member-level',
        meta: {
          title: 'marketing_member-level',
          i18nKey: 'route.marketing_member-level'
        }
      },
      {
        name: 'marketing_member-points-record',
        path: '/marketing/member-points-record',
        component: 'view.marketing_member-points-record',
        meta: {
          title: 'marketing_member-points-record',
          i18nKey: 'route.marketing_member-points-record'
        }
      },
      {
        name: 'marketing_member-stat',
        path: '/marketing/member-stat',
        component: 'view.marketing_member-stat',
        meta: {
          title: 'marketing_member-stat',
          i18nKey: 'route.marketing_member-stat'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_message',
        path: '/monitor/message',
        component: 'view.monitor_message',
        meta: {
          title: 'monitor_message',
          i18nKey: 'route.monitor_message'
        }
      }
    ]
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base',
    meta: {
      title: 'order',
      i18nKey: 'route.order'
    },
    children: [
      {
        name: 'order_detail',
        path: '/order/detail',
        component: 'view.order_detail',
        meta: {
          title: 'order_detail',
          i18nKey: 'route.order_detail'
        }
      },
      {
        name: 'order_list',
        path: '/order/list',
        component: 'view.order_list',
        meta: {
          title: 'order_list',
          i18nKey: 'route.order_list'
        }
      }
    ]
  },
  {
    name: 'report',
    path: '/report',
    component: 'layout.base',
    meta: {
      title: '数据报表',
      icon: 'mdi:chart-bar',
      order: 5,
      i18nKey: 'route.report'
    },
    children: [
      {
        name: 'report_dish-ranking',
        path: '/report/dish-ranking',
        component: 'view.report_dish-ranking',
        meta: {
          title: 'report_dish-ranking',
          i18nKey: 'route.report_dish-ranking'
        }
      },
      {
        name: 'report_revenue',
        path: '/report/revenue',
        component: 'view.report_revenue',
        meta: {
          title: 'report_revenue',
          i18nKey: 'route.report_revenue'
        }
      },
      {
        name: 'report_table-turnover',
        path: '/report/table-turnover',
        component: 'view.report_table-turnover',
        meta: {
          title: '翻台率',
          icon: 'mdi:rotate-3d-variant',
          i18nKey: 'route.report_table-turnover'
        }
      }
    ]
  },
  {
    name: 'service',
    path: '/service',
    component: 'layout.base',
    meta: {
      title: 'service',
      i18nKey: 'route.service'
    },
    children: [
      {
        name: 'service_checkout',
        path: '/service/checkout',
        component: 'view.service_checkout',
        meta: {
          title: 'service_checkout',
          i18nKey: 'route.service_checkout'
        }
      },
      {
        name: 'service_kitchen',
        path: '/service/kitchen',
        component: 'view.service_kitchen',
        meta: {
          title: 'service_kitchen',
          i18nKey: 'route.service_kitchen'
        }
      },
      {
        name: 'service_order-ops',
        path: '/service/order-ops',
        component: 'view.service_order-ops',
        meta: {
          title: 'service_order-ops',
          i18nKey: 'route.service_order-ops'
        }
      },
      {
        name: 'service_place-order',
        path: '/service/place-order',
        component: 'view.service_place-order',
        meta: {
          title: 'service_place-order',
          i18nKey: 'route.service_place-order'
        }
      },
      {
        name: 'service_table-board',
        path: '/service/table-board',
        component: 'view.service_table-board',
        meta: {
          title: 'service_table-board',
          i18nKey: 'route.service_table-board'
        }
      }
    ]
  },
  {
    name: 'table',
    path: '/table',
    component: 'layout.base',
    meta: {
      title: 'table',
      i18nKey: 'route.table'
    },
    children: [
      {
        name: 'table_area',
        path: '/table/area',
        component: 'view.table_area',
        meta: {
          title: 'table_area',
          i18nKey: 'route.table_area'
        }
      },
      {
        name: 'table_manage',
        path: '/table/manage',
        component: 'view.table_manage',
        meta: {
          title: 'table_manage',
          i18nKey: 'route.table_manage'
        }
      }
    ]
  }
];
