import test from 'node:test';import assert from 'node:assert/strict';import {installCustomerViewport} from '../viewport.js';
function fixture(){const values=new Map(),listeners=new Map(),sizes={width:390,height:660,offsetLeft:0,offsetTop:0},meta={content:'width=device-width, initial-scale=1',getAttribute(){return this.content},setAttribute(k,v){this.content=v}};let clock=1000;const doc={documentElement:{classList:{add(){},remove(){}},style:{getPropertyValue:k=>values.get(k)||'',setProperty:(k,v)=>values.set(k,v),removeProperty:k=>values.delete(k)}},querySelector:()=>meta,addEventListener:(k,f)=>listeners.set(k,f),removeEventListener:k=>listeners.delete(k)};const win={innerWidth:390,innerHeight:660,visualViewport:{...sizes,addEventListener(){},removeEventListener(){}},performance:{now:()=>clock},requestAnimationFrame:f=>{f();return 1},cancelAnimationFrame(){},addEventListener(){},removeEventListener(){}};const cleanup=installCustomerViewport(win,doc);const event=(type,touches,target={closest:()=>null},changes=touches)=>{const e={touches,changedTouches:changes,target,cancelable:true,preventDefault(){this.defaultPrevented=true},defaultPrevented:false};listeners.get(type)(e);return e};return{win,doc,meta,values,event,cleanup,advance:ms=>clock+=ms,listeners}}
const touch=(x=20,y=20)=>({clientX:x,clientY:y});
test('Uses the visible viewport and requests an unscaled customer frame',()=>{const f=fixture();assert.equal(f.values.get('--customer-height'),'660px');assert(f.meta.content.includes('user-scalable=no'));assert.equal(f.values.get('--customer-width'),'390px')});
test('Pinch start/move are canceled',()=>{const f=fixture();assert(f.event('touchstart',[touch(),touch(40)]).defaultPrevented);assert(f.event('touchmove',[touch(),touch(50)]).defaultPrevented)});
test('Single finger scrolling remains usable',()=>{const f=fixture();assert(!f.event('touchstart',[touch()]).defaultPrevented);assert(!f.event('touchmove',[touch(20,100)]).defaultPrevented);assert(!f.event('touchend',[],undefined,[touch(20,100)]).defaultPrevented)});
test('A nearby rapid double tap on noninteractive content is suppressed',()=>{const f=fixture();f.event('touchstart',[touch()]);f.event('touchend',[],undefined,[touch()]);f.advance(100);f.event('touchstart',[touch()]);assert(f.event('touchend',[],undefined,[touch()]).defaultPrevented)});
test('Rapid quantity-button taps are not swallowed',()=>{const f=fixture(),button={closest:()=>({tagName:'BUTTON'})};for(let i=0;i<2;i++){f.event('touchstart',[touch()],button);assert(!f.event('touchend',[],button,[touch()]).defaultPrevented);f.advance(100)}});
test('A swipe followed by a tap does not count as a double tap',()=>{const f=fixture();f.event('touchstart',[touch()]);f.event('touchmove',[touch(20,100)]);f.event('touchend',[],undefined,[touch(20,100)]);f.advance(100);f.event('touchstart',[touch(20,100)]);assert(!f.event('touchend',[],undefined,[touch(20,100)]).defaultPrevented)});
test('WebKit gesture fallback is canceled',()=>{const f=fixture();assert(f.event('gesturestart',[]).defaultPrevented);assert(f.event('gesturechange',[]).defaultPrevented)});
test('Cleanup restores the original viewport and removes touch listeners',()=>{const f=fixture();f.cleanup();assert.equal(f.meta.content,'width=device-width, initial-scale=1');assert.equal(f.listeners.size,0);assert(!f.values.has('--customer-height'))});
