/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "device": "/device";
    "device_audit-log": "/device/audit-log";
    "device_feedback": "/device/feedback";
    "device_payment": "/device/payment";
    "device_printer": "/device/printer";
    "device_review": "/device/review";
    "device_review_detail": "/device/review/detail";
    "dish": "/dish";
    "dish_category": "/dish/category";
    "dish_list": "/dish/list";
    "dish_spec": "/dish/spec";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "log": "/log";
    "log_login": "/log/login";
    "log_operation": "/log/operation";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "manage": "/manage";
    "manage_banner": "/manage/banner";
    "manage_config": "/manage/config";
    "manage_coupon": "/manage/coupon";
    "manage_dict": "/manage/dict";
    "manage_member-user": "/manage/member-user";
    "manage_menu": "/manage/menu";
    "manage_mq-message": "/manage/mq-message";
    "manage_role": "/manage/role";
    "manage_theme": "/manage/theme";
    "manage_user": "/manage/user";
    "marketing": "/marketing";
    "marketing_banner": "/marketing/banner";
    "marketing_coupon": "/marketing/coupon";
    "marketing_member": "/marketing/member";
    "marketing_member-benefit": "/marketing/member-benefit";
    "marketing_member-growth-record": "/marketing/member-growth-record";
    "marketing_member-level": "/marketing/member-level";
    "marketing_member-points-record": "/marketing/member-points-record";
    "marketing_member-stat": "/marketing/member-stat";
    "monitor": "/monitor";
    "monitor_message": "/monitor/message";
    "order": "/order";
    "order_detail": "/order/detail";
    "order_list": "/order/list";
    "report": "/report";
    "report_dish-ranking": "/report/dish-ranking";
    "report_revenue": "/report/revenue";
    "report_table-turnover": "/report/table-turnover";
    "service": "/service";
    "service_checkout": "/service/checkout";
    "service_kitchen": "/service/kitchen";
    "service_order-ops": "/service/order-ops";
    "service_place-order": "/service/place-order";
    "service_table-board": "/service/table-board";
    "table": "/table";
    "table_area": "/table/area";
    "table_manage": "/table/manage";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "device"
    | "dish"
    | "home"
    | "iframe-page"
    | "log"
    | "login"
    | "manage"
    | "marketing"
    | "monitor"
    | "order"
    | "report"
    | "service"
    | "table"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "device_audit-log"
    | "device_feedback"
    | "device_payment"
    | "device_printer"
    | "device_review_detail"
    | "device_review"
    | "dish_category"
    | "dish_list"
    | "dish_spec"
    | "home"
    | "log_login"
    | "log_operation"
    | "manage_banner"
    | "manage_config"
    | "manage_coupon"
    | "manage_dict"
    | "manage_member-user"
    | "manage_menu"
    | "manage_mq-message"
    | "manage_role"
    | "manage_theme"
    | "manage_user"
    | "marketing_banner"
    | "marketing_coupon"
    | "marketing_member-benefit"
    | "marketing_member-growth-record"
    | "marketing_member-level"
    | "marketing_member-points-record"
    | "marketing_member-stat"
    | "marketing_member"
    | "monitor_message"
    | "order_detail"
    | "order_list"
    | "report_dish-ranking"
    | "report_revenue"
    | "report_table-turnover"
    | "service_checkout"
    | "service_kitchen"
    | "service_order-ops"
    | "service_place-order"
    | "service_table-board"
    | "table_area"
    | "table_manage"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
